# ============================================================================
# generate_plot.py — Weather data plotting (Plotly HTML only)
# ============================================================================
# Reads Parquet files generated by fetch_data.py and produces:
#   - Dry Bulb + Black Bulb Temperature (HTML)
#   - Humidity (HTML)
#   - Battery (HTML)
#   - Dewpoint (HTML, computed)
# ============================================================================

import os
import pandas as pd
import plotly.express as px
import numpy as np

DATA_DIR = "data"

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------

def load_latest():
    """Load latest.parquet, normalize column names, ensure datetime index."""
    path = os.path.join(DATA_DIR, "latest.parquet")
    if not os.path.exists(path):
        raise FileNotFoundError("latest.parquet not found. Run fetch_data.py first.")

    df = pd.read_parquet(path)
    df.index = pd.to_datetime(df.index)

    # Normalize column names
    df = df.rename(columns={
        "TempC_SHT": "dry_bulb",     # Dry Bulb Temperature
        "TempC_DS": "black_bulb",    # Black Bulb Temperature
        "Hum_SHT": "hum",
        "BatV": "bat"
    })

    return df.sort_index()


def ensure_output_dir():
    os.makedirs(DATA_DIR, exist_ok=True)


# ----------------------------------------------------------------------------
# Dewpoint Calculation (Magnus formula)
# ----------------------------------------------------------------------------

def compute_dewpoint(df):
    """Compute dewpoint from dry bulb temperature and humidity."""
    if "dry_bulb" not in df.columns or "hum" not in df.columns:
        print("Skipping dewpoint calculation — missing dry_bulb or hum.")
        return df

    T = df["dry_bulb"]
    RH = df["hum"]

    # Magnus constants for water
    a = 17.62
    b = 243.12  # °C

    gamma = (a * T / (b + T)) + np.log(RH / 100.0)
    dewpoint = (b * gamma) / (a - gamma)

    df["dewpoint"] = dewpoint
    return df


# ----------------------------------------------------------------------------
# Plotly HTML Plots
# ----------------------------------------------------------------------------

def plotly_temperature_html(df):
    required = ["dry_bulb", "black_bulb"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        print(f"Skipping temperature HTML — missing columns: {missing}")
        return

    fig = px.line(
        df,
        x=df.index,
        y=["dry_bulb", "black_bulb"],
        title="Dry Bulb & Black Bulb Temperature (Interactive)",
        labels={"value": "Temperature (°C)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_temperature.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


def plotly_humidity_html(df):
    if "hum" not in df.columns:
        print("Skipping humidity HTML — no 'hum' column found.")
        return

    fig = px.line(
        df,
        x=df.index,
        y="hum",
        title="Humidity (Interactive)",
        labels={"hum": "Humidity (%)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_humidity.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


def plotly_battery_html(df):
    if "bat" not in df.columns:
        print("Skipping battery HTML — no 'bat' column found.")
        return

    fig = px.line(
        df,
        x=df.index,
        y="bat",
        title="Battery Voltage (Interactive)",
        labels={"bat": "Battery (V)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_battery.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


def plotly_dewpoint_html(df):
    if "dewpoint" not in df.columns:
        print("Skipping dewpoint HTML — no dewpoint column found.")
        return

    fig = px.line(
        df,
        x=df.index,
        y="dewpoint",
        title="Dewpoint (Interactive)",
        labels={"dewpoint": "Dewpoint (°C)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_dewpoint.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main():
    ensure_output_dir()
    df = load_latest()

    # Compute dewpoint
    df = compute_dewpoint(df)

    print("Generating Plotly HTML plots...")
    plotly_temperature_html(df)
    plotly_humidity_html(df)
    plotly_battery_html(df)
    plotly_dewpoint_html(df)

    print("✓ All Plotly plots generated successfully")


if __name__ == "__main__":
    main()
