# ============================================================================
# generate_plot.py — Weather data plotting (PNG + Plotly HTML)
# ============================================================================
# Reads Parquet files generated by fetch_data.py and produces:
#   - Temperature/Humidity PNG
#   - Battery PNG
#   - Dewpoint PNG
#   - Interactive Plotly HTML versions
# ============================================================================

import os
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime

DATA_DIR = "data"

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------

def load_latest():
    """Load latest.parquet and ensure datetime index."""
    path = os.path.join(DATA_DIR, "latest.parquet")
    if not os.path.exists(path):
        raise FileNotFoundError("latest.parquet not found. Run fetch_data.py first.")

    df = pd.read_parquet(path)
    df.index = pd.to_datetime(df.index)
    return df.sort_index()


def ensure_output_dir():
    """Ensure output directory exists."""
    os.makedirs(DATA_DIR, exist_ok=True)


# ----------------------------------------------------------------------------
# Matplotlib PNG Plots
# ----------------------------------------------------------------------------

def plot_temp_humidity_png(df):
    """Generate temperature + humidity PNG plot."""
    fig, ax1 = plt.subplots(figsize=(12, 6))

    ax1.set_title("Temperature & Humidity Over Time")
    ax1.set_xlabel("Time (UTC)")

    # Temperature
    ax1.plot(df.index, df["temp"], color="tab:red", label="Temperature (°C)")
    ax1.set_ylabel("Temperature (°C)", color="tab:red")
    ax1.tick_params(axis="y", labelcolor="tab:red")

    # Humidity
    ax2 = ax1.twinx()
    ax2.plot(df.index, df["hum"], color="tab:blue", label="Humidity (%)")
    ax2.set_ylabel("Humidity (%)", color="tab:blue")
    ax2.tick_params(axis="y", labelcolor="tab:blue")

    fig.tight_layout()
    out_path = os.path.join(DATA_DIR, "plot_temp_humidity.png")
    plt.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved: {out_path}")


def plot_battery_png(df):
    """Generate battery voltage PNG plot."""
    fig, ax = plt.subplots(figsize=(12, 4))

    ax.plot(df.index, df["bat"], color="tab:green")
    ax.set_title("Battery Voltage Over Time")
    ax.set_xlabel("Time (UTC)")
    ax.set_ylabel("Battery (V)")

    fig.tight_layout()
    out_path = os.path.join(DATA_DIR, "plot_battery.png")
    plt.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved: {out_path}")


def plot_dewpoint_png(df):
    """Generate dewpoint PNG plot if dewpoint exists."""
    if "dewpoint" not in df.columns:
        print("Skipping dewpoint plot — no dewpoint column found.")
        return

    fig, ax = plt.subplots(figsize=(12, 4))

    ax.plot(df.index, df["dewpoint"], color="tab:purple")
    ax.set_title("Dewpoint Over Time")
    ax.set_xlabel("Time (UTC)")
    ax.set_ylabel("Dewpoint (°C)")

    fig.tight_layout()
    out_path = os.path.join(DATA_DIR, "plot_dewpoint.png")
    plt.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved: {out_path}")


# ----------------------------------------------------------------------------
# Plotly HTML Plots
# ----------------------------------------------------------------------------

def plotly_temp_humidity_html(df):
    fig = px.line(
        df,
        x=df.index,
        y=["temp", "hum"],
        title="Temperature & Humidity (Interactive)",
        labels={"value": "Measurement", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_temp_humidity.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


def plotly_battery_html(df):
    fig = px.line(
        df,
        x=df.index,
        y="bat",
        title="Battery Voltage (Interactive)",
        labels={"bat": "Battery (V)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_battery.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


def plotly_dewpoint_html(df):
    if "dewpoint" not in df.columns:
        print("Skipping dewpoint HTML — no dewpoint column found.")
        return

    fig = px.line(
        df,
        x=df.index,
        y="dewpoint",
        title="Dewpoint (Interactive)",
        labels={"dewpoint": "Dewpoint (°C)", "index": "Time (UTC)"}
    )
    out_path = os.path.join(DATA_DIR, "plot_dewpoint.html")
    fig.write_html(out_path)
    print(f"Saved: {out_path}")


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main():
    ensure_output_dir()
    df = load_latest()
    print("Columns in latest.parquet:", df.columns.tolist())

    print("Generating PNG plots...")
    plot_temp_humidity_png(df)
    plot_battery_png(df)
    plot_dewpoint_png(df)

    print("Generating HTML plots...")
    plotly_temp_humidity_html(df)
    plotly_battery_html(df)
    plotly_dewpoint_html(df)

    print("✓ All plots generated successfully")


if __name__ == "__main__":
    main()
